
import java.io.PrintWriter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * user_form.java
 *
 * Created on Apr 1, 2013, 5:58:16 PM
 */
/**
 *
 * @@author Daniel
 */
public class user_form extends javax.swing.JFrame {

    /** Creates new form user_form */
    public user_form() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        find_direction = new javax.swing.JButton();
        update_graph = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        find_direction.setText("Find Direction");
        find_direction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_directionActionPerformed(evt);
            }
        });

        update_graph.setText("Update Graph");
        update_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_graphActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome to my applet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(find_direction)
                        .addGap(53, 53, 53)
                        .addComponent(update_graph))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(find_direction)
                    .addComponent(update_graph))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void find_directionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_directionActionPerformed
     this.setVisible(false);
     new user_find_direction().setVisible(true);
    // to_do action perform here1
    // TODO add your handling code here:
}//GEN-LAST:event_find_directionActionPerformed

private void update_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_graphActionPerformed

    //******************************************
    this.setVisible(false);
    new manager_log_in().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_update_graphActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
         manager m = new manager("admin","admin","manager");
       
       

                try
                {
                        // Create a new file output stream
                        // connected to "profile.txt"
                       PrintWriter out = new PrintWriter("manager.txt");

                        // Connect print stream to the output stream
                       // p = new PrintStream( out );
		
                        out.println (m.toString());

                        out.close();
                }
                catch (Exception e)
                {
                        System.err.println ("Error writing to file");
                }
               /* //****************************************************
                 try
                {
                        // Create a new file output stream
                        // connected to "profile.txt"
                       PrintWriter out1 = new PrintWriter("Node.txt");

                        // Connect print stream to the output stream
                       // p = new PrintStream( out );
		
                       

                        out1.close();
                }
                catch (Exception e)
                {
                        System.err.println ("Error writing to file");
                }
                //****************************************************
                  try
                {
                        // Create a new file output stream
                        // connected to "profile.txt"
                       PrintWriter out2 = new PrintWriter("Edge.txt");

                        // Connect print stream to the output stream
                       // p = new PrintStream( out );
		
                       

                        out2.close();
                }
                catch (Exception e)
                {
                        System.err.println ("Error writing to file");
                }*/
                 //***************************************************
        java.awt.EventQueue.invokeLater(new Runnable() {
             
            public void run() {
                
                //new user_form().setBounds(0, 0, 400, 500);  
              
              final user_form d = new user_form();
               
                d.setLocation(400,400);
               // new user_form().setBounds(11, 15, 500, 500);
                d.setVisible(true);
                new user_find_direction().setVisible(false);
                new manager_log_in().setVisible(false);
                new manager_form().setVisible(false);
                new Delete_road().setVisible(false);
                new Create_graph().setVisible(false);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton find_direction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton update_graph;
    // End of variables declaration//GEN-END:variables
}
